SELECT S.USER_ID, 
COALESCE(ROUND(SUM(CASE WHEN c.action = 'confirmed' THEN 1 ELSE 0 END) * 1.0 / NULLIF(COUNT(C.ACTION), 0), 2),0) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C
ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID;